name: animated_border_widgets_example
description: Example app for animated_border_widgets.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  animated_border_widgets:
    path: ..

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
